server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path(route='about', view=views.about, name="about"),

    # path for contact us view
    path(route='contact', view=views.contact, name="contact"),

    # path for registration
    path('registration', views.registration_request, name='registration'),

    # path for login
    path('login', views.login_request, name='login'),

    # path for logout
    path('logout', views.logout_request, name='logout'),

    # path for dealer reviews view
    path(route='dealer/<int:dealer_id>/', view=views.get_dealer_details, name='dealer_details'),

    # path for home, index page
    path(route='', view=views.get_dealerships, name='index'),
    
    # path for add a review view
     path(route='dealer/<int:dealer_id>/add_review/', view=views.add_review, name="add_review")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):
    name = models.CharField(null=False, max_length=50)
    description = models.CharField(null=True, max_length=500)

    def __str__(self):
        return self.name

# <HINT> Create a Car Model model `class CarModel(models.Model):`:

class CarModel(models.Model):
    # make = models.ForeignKey(CarMake, null=True, on_delete = models.CASCADE)
    car_make = models.ForeignKey(CarMake, null=True, on_delete=models.CASCADE)
    dealer_id = models.IntegerField()
    name = models.CharField(max_length=255)
    SEDAN = "Sedan"
    SUV = "SUV"
    WAGON = "WAGON"
    TYPE_CHOICES = (
        (SEDAN, "Sedan"),
        (SUV, "SUV"),
        (WAGON, "Wagon"),
    )
    model_type  = models.CharField(max_length=10, choices=TYPE_CHOICES)
    year = models.DateField()

    def __str__(self):
        return f"{self.car_make} {self.name} ({self.year})"

        
# <HINT> Create a plain Python class `CarDealer` to hold dealer data

# All fields are from dealerships document in cloudant
class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip

    def __str__(self):
        return "Dealer name: " + self.full_name


# <HINT> Create a plain Python class `DealerReview` to hold review data

# All fields are from review documet in cloudant
class DealerReview:

    def __init__(self, id, name, dealership, review, purchase, purchase_date, car_make, car_model, car_year, sentiment='neutral'):
        self.id = id
        self.name = name  # reviewer name
        self.dealership = dealership
        self.review = review  # reveiw text
        self.purchase = purchase  # Did the reviewer purchase the car? bool
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment  # Watson NLU sentiment analysis of review

        def __str__(self):
            return 'Reviewer: ' + self.name + ' Review: ' + self.review

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
# from .models import related models
# from .restapis import related methods
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
from django.urls import reverse
import logging
import json

from .restapis import get_dealers_from_cf, get_dealer_by_id_from_cf, get_dealer_reviews_from_cf, post_request

from django.views.decorators.csrf import csrf_exempt, csrf_protect

from .models import CarModel, CarDealer

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    if request.method == "GET":
        return render(request, "djangoapp/contact.html", context)

# Create a `login_request` view to handle sign in request
def login_request(request):
    context = {}
    # handle post request
    if request.method == "POST":
        # get use name and password from post request
        username = request.POST['username']
        password = request.POST['psw']

        # authenticate user
        user = authenticate(username=username, password=password)
        # if authorized log in and redirect else do not login
        if user is not None:
            login(request, user)
            return redirect("djangoapp:index")
        else:
            return redirect("djangoapp/index.html")
    else:
        return redirect("djangoapp/index.html")


# Create a `logout_request` view to handle sign out request
def logout_request(request):
    # Get the user object based on session id in request
    print("Log out the user `{}`".format(request.user.username))
    # Logout user in the request
    logout(request)
    # Redirect user back to course list view
    return redirect('djangoapp:index')


# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}
    # If it is a GET request, just render the registration page
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    # If it is a POST request
    elif request.method == 'POST':
        # Get user information from request.POST
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            # Check if user already exists
            User.objects.get(username=username)
            user_exist = True
        except:
            # If not, simply log this is a new user
            logger.debug("{} is new user".format(username))
        # If it is a new user
        if not user_exist:
            # Create user in auth_user table
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            # Login the user and redirect to course list page
            login(request, user)
            return redirect("djangoapp:index")
        else:
            return render(request, 'djangoapp/registration.html', context)

# Update the `get_dealerships` view to render the index page with a list of dealerships
# make request to node.js server: get-dealerships.js
def get_dealerships(request):
    if request.method == "GET":
        context = {}
        # https://devshahfahad-8000.theiadockernext-0-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/djangoapp
        # url = "https://devshahfahad-3000.theiadockernext-0-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai/dealerships/get"
        url = "http://localhost:3000/dealerships/get"
        dealerships = get_dealers_from_cf(url)
        context["dealership_list"] = dealerships
        
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
# make request to flask server: reviews.py
def get_dealer_details(request, dealer_id):
    print(request, dealer_id)
    if request.method == "GET":
        context = {}
        url = f"http://127.0.0.1:5000/api/get_reviews?id={dealer_id}"
        # Get dealers from the URL
        reviews = get_dealer_reviews_from_cf(url)
        # Concat all dealer's short name
        dealer_names = " ".join([dealer.name for dealer in reviews])
        # Return a list of dealer short name
        
        context = {"reviews" :reviews, "dealer_id": dealer_id}
        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review
@csrf_exempt
def add_review(request, dealer_id):
    # User must be logged in before posting a review
    if request.user.is_authenticated or True:
        # GET request renders the page with the form for filling out a review
        if request.method == "GET":
            # url = f"http://localhost:3000/dealerships/get?dealerId={dealer_id}"
            url = "http://localhost:3000/dealerships/get"
            # Get dealer details from the API
            # Get dealer details from the API
            dealer = get_dealer_by_id_from_cf(url, dealer_id=dealer_id) # return [{}, {dealer object}]
            # temprory solution is to extract dealer object at index 1: dealer[1]
            context = {
                "cars": CarModel.objects.all(),
                "dealer": dealer[1],
            }
            
            return render(request, 'djangoapp/add_review.html', context)
        
        # POST request posts the content in the review submission form to the Cloudant DB using the post_review Cloud Function
        if request.method == "POST":
            # Get data from request
            review_post_json_data = request.POST # Loads data only from form
            # review_post_json_data = json.loads(request.body) # Loads json data from post request
            print("AT POST REQUEST: ")
            print(request.POST)
            # Store data to review dictionary one by one
            review = {}
            review["id"] = review_post_json_data.get("id")
            review["name"] = review_post_json_data.get("name")
            review["dealership"] = dealer_id
            review["review"] = review_post_json_data.get("review")
            review["purchase"] = review_post_json_data.get("purchase", False)  # Default to False if not present

            if review["purchase"]:
                purchase_date_str = review_post_json_data.get("purchase_date")
                purchase_date_str = review_post_json_data.get("purchase_date")
                if purchase_date_str:
                    purchase_date = datetime.strptime(purchase_date_str, "%m/%d/%Y")
                    review["purchase_date"] = purchase_date.strftime("%m/%d/%Y")
                else:
                    review["purchase_date"] = None
            else:
                review["purchase_date"] = None

            print("AT Review:  ")
            print(review)
            car = get_object_or_404(CarModel, pk=review["id"])
            review["car_make"] = car.car_make.name
            review["car_model"] = car.name
            review["car_year"] = car.year.strftime("%Y")
            
        #     # make reques to this url: flask server: reviews.py
            url = "http://127.0.0.1:5000/api/post_review"  # API Cloud Function route
            json_payload = {"review": review}  # Create a JSON payload that contains the review data
            
            # Performing a POST request with the review
            print("JSON PAYLOAD IS HERE: ", json_payload)
            # After posting the review the user is redirected back to the dealer details page
            return redirect("djangoapp:dealer_details", dealer_id=dealer_id)
            

    # If user isn't logged in, redirect to login page
    print("User must be authenticated before posting a review. Please log in.")
    return redirect("/djangoapp/login")

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Us</title>
</head>

    <body>
        <h1>
            Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
        </h1>
    </body>

</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% load static %}
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css"
      rel="stylesheet"
    />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
  </head>
  <body>
    <!--Add review form here -->
<h1>Add Review for : {{ dealer.full_name }}</h1>
<hr class="dropdown-divider">
    <form action="{% url 'djangoapp:add_review' dealer.id %}" method="post">
      {% csrf_token %}
      {% comment %} Send name and id in hidden input {% endcomment %}
      <input type="hidden" name="id" value={{ dealer.id }}>
      <input type="hidden" name="name" value= {{ dealer.full_name }}>
            <div class="form-group">
                <label for="content"><b>Enter the review content:</b></label>
                <textarea class="form-control" id="content" name="review" rows="2" required></textarea>
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" name="purchase" id="purchasecheck">
                <label for="purchasecheck">Did you purchase the car? </label>
            </div>
            <div class="form-group">
                <label for="car">Select your car:</label>
                <select name="car" id="car" class="form-select">
                    {% for car in cars %}
                        <option selected value={{car.id}}>{{car.car_make.name}} {{car.name}} {{ car.year }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group" data-provide="datepicker">
                <label for="purchasedate">Select your purchase date (mm/dd/yyyy):</label>
                <input class="date-own form-control" type="text" name="purchase_date" id="purchasedate">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
  </body>
  <script type="text/javascript">
        $('.date-own').datepicker({
           format: 'mm/dd/yyyy'
         });
   </script>
</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Us</title>
</head>

    <body>
        <div>
            <h1>Address</h1>
             <p>North America</p> 

             <h1>Telephone No.</h1>
             <p>123456789</p> 
        </div>
    </body>

</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review</title>
    {% load static %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
  </head>

  <body>
    <!--Add a nav bar here -->
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Dealership Review</a>
        </div>
        <ul class="nav navbar-nav navbar-right list-group-horizontal">
          <li>
            <a class="btn btn-link" href="{% url 'djangoapp:about' %}">About</a>
            <a class="btn btn-link" href="{% url 'djangoapp:contact' %}"
              >Contact</a
            >
          </li>
          {% if user.is_authenticated %}
          <li>
            <a class="btn btn-link" href="#"
              >{{ user.first_name }}({{ user.username }})</a
            >
            <a class="btn btn-link" href="{% url 'djangoapp:logout' %}"
              >Logout</a
            >
            {% if dealer_id %}
            <a
              class="btn btn-link"
              href="{% url 'djangoapp:add_review' dealer_id %}"
              >Add Review {{dealer_id}}</a
            >
            {% endif %}
          </li>
          {% else %}
          <li>
            <form
              class="form-inline"
              action="{% url 'djangoapp:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Password"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a
                  class="btn btn-link"
                  href="{% url 'djangoapp:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% if reviews %}
    <!-- Add reviews as cards -->
    <div class="card-columns">
      {% for review in reviews %}
      <div class="card">
        {% if review.sentiment == "positive"%}
        <img class="card-img-left" src="{{MEDIA_URL}}emoji/positive.png" />
        {% elif review.sentiment == "neutral" %}
        <img class="card-img-left" src="{{MEDIA_URL}}emoji/neutral.png" />
        {% elif review.sentiment == "negative" %}
        <img class="card-img-left" src="{{MEDIA_URL}}emoji/negative.png" />
        {%else %}
        <img class="card-img-left" src="{{MEDIA_URL}}emoji/neutral.png" />
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ review.car_model }}</h5>

          <h6 class="card-subtitle mb-2 text-muted">{{ review.car_make }}</h6>

          <p class="card-text">{{ review.review }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <h1 class="text-center">No, reviews are available.</h1>
    {% endif %}
  </body>
</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dealership Review</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link
      href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css"
      rel="stylesheet"
    />
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
  </head>

  <body>
    <!--Add a nav bar here -->
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Dealership Review</a>
        </div>
        <ul class="nav navbar-nav navbar-right list-group-horizontal">
          <li>
            <a class="btn btn-link" href="{% url 'djangoapp:about' %}">About</a>
            <a class="btn btn-link" href="{% url 'djangoapp:contact' %}"
              >Contact</a
            >
          </li>
          {% if user.is_authenticated %}
          <li>
            <a class="btn btn-link" href="#"
              >{{ user.first_name }}({{ user.username }})</a
            >
            <a class="btn btn-link" href="{% url 'djangoapp:logout' %}"
              >Logout</a
            >
          </li>
          {% else %}
          <li>
            <form
              class="form-inline"
              action="{% url 'djangoapp:login' %}"
              method="post"
            >
              {% csrf_token %}
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  placeholder="Username"
                  name="username"
                />
                <input
                  type="password"
                  class="form-control"
                  placeholder="Password"
                  name="psw"
                />
                <button class="btn btn-primary" type="submit">Login</button>
                <a
                  class="btn btn-link"
                  href="{% url 'djangoapp:registration' %}"
                  >Sign Up</a
                >
              </div>
            </form>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!--Add a dealer table here -->
    <table class="table" id="table" data-filter-control="true">
      <thead>
        <tr>
          <th data-field="id">ID</th>
          <th data-field="name">Dealer Name</th>
          <th data-field="city">City</th>
          <th data-field="addresss">Address</th>
          <th data-field="zip">Zip</th>
          <th data-field="state" data-filter-control="select">State</th>
        </tr>
      </thead>
      <tbody>
        {% for dealer in dealership_list %}
        <tr>
          <td>{{dealer.id}}</td>
          <td>
            <a href="{% url 'djangoapp:dealer_details' dealer.id %}"
              >{{dealer.full_name}}</a
            >
          </td>
          <td>{{dealer.city}}</td>
          <td>{{dealer.address}}</td>
          <td>{{dealer.zip}}</td>
          <td>{{dealer.st}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
  <!-- turn-on filter control for the table -->
  <script>
    $(function () {
      $("#table").bootstrapTable();
    });
  </script>
</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>
    <body>
    <!--Add a registration form here -->
    <form action="{% url 'djangoapp:registration' %}" method="post">
        <div class="container">
          <h1>Sign Up</h1>
          <hr>
          <div class="form-group">
              <label for="username"><b>User Name</b></label>
          </br>
              <input class="form-control" type="text" placeholder="Enter User Name: " name="username" required>
          </div>
          <div class="form-group">
            <label for="firstname"><b>First Name</b></label>
          </br>
            <input class="form-control" type="text" placeholder="Enter First Name: " name="firstname" required>
          </div>
          <div class="form-group">
            <label for="lastname"><b>Last Name</b></label>
          </br>
            <input class="form-control" type="text" placeholder="Enter Last Name: " name="lastname" required>
          </div>
          <div class="form-group">
          <label for="psw"><b>Password</b></label>
        </br>
          <input class="form-control" type="password" placeholder="Enter Password: " name="psw" required>
          </div>
          <div>
              {% csrf_token %}
              <button class="btn btn-primary" type="submit">Sign Up</button>
          </div>
        </div>
      </form>

    </body>
</html>